directories:
  output: release
  buildResources: build
appId: com.pixel.app
productName: Pixel
copyright: Copyright © 2024
files:
  - filter:
      - main.js
      - preload.js
extraResources:
  - from: electron-web
    to: electron-web
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
mac:
  target: dmg
linux:
  target: AppImage
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Pixel
electronVersion: 33.4.11
