// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pixel-home/CommandCentre.tsx": () => import("../components/mockups/pixel-home/CommandCentre.tsx"),
  "./components/mockups/pixel-home/FocusedFlow.tsx": () => import("../components/mockups/pixel-home/FocusedFlow.tsx")
};
